### ISSUE TITLE
Consider using http.ServeContent instead of io.Copy

### ISSUE THREAD

**Issue by ToMGitHubN** [domZippilli/gcs-proxy-cloud-run#11]
Hello.
I read your nice tutorial.https://cloud.google.com/community/tutorials/cloud-run-golang-gcs-proxy
I needed a simple proxy.

The problem I encountered is that some files cannot be displayed in safari.
The cause is that it does not support HTTP range requests.
https://blog.logrocket.com/streaming-video-in-safari/

golang supports HTTP range requests.
 io.Copy -> http.ServeContent 
https://stackoverflow.com/questions/36540610/how-to-serve-http-partial-content-with-go
https://pkg.go.dev/net/http#ServeContent

```
The main benefit of ServeContent over io.Copy is that it handles Range requests properly, sets the MIME type, and handles If-Match, If-Unmodified-Since, If-None-Match, If-Modified-Since, and If-Range requests.
```

Thank you for reading.

**Comment by domZippilli** [comment]
Hi,

Sorry it took me so long to get back to you. I hit a very busy period at work and family. I imagine you may have moved on and used another proxy/architecture by now, but I still wanted to look into this.

So, I looked into it today. I'd like to use `http.ServeContent`, and I think I did consider it at one point when originally writing this. There are a few reasons I don't think we can do that in this proxy.

[`http.ServeContent`](https://pkg.go.dev/net/http#ServeContent) requires an `io.ReadSeeker` for the `content` argument, and the media stream I get back from GCS is not seekable (it's an `io.Reader`). Converting between the two is not easy. The trivial conversion is to load the response into a `bytes.Buffer` and make a `ReadSeeker` from that... but that requires loading the whole response into memory which will break streaming, and convert this proxy to a [store-and-forward](https://en.wikipedia.org/wiki/Transmission_delay) design. Then, I thought I could just implement the seek method to discard bytes up to the seek offset, and _hope_ that `http.ServeContent` will never try to "rewind" the stream and seek to an earlier offset. However, I'm pretty sure it does exactly that, because of this line from the docs linked above:

```
The content's Seek method must work: ServeContent uses a seek to the end of the content to determine its size.
```

So, even with a "fast-forward" seeker, `ServeContent` would force it to read all bytes just to get the size (wish I could just pass a length value, but I don't see that option 😞) Then, it's going to have to seek back to offset=0 (or the first byte of the range(s)). So my Reader->ReadSeeker conversion _has_ to rewind. Therefore, this will only work if we load all of the response bytes into memory before serving any.

We might be able to circumvent this by decoupling the 1:1 FE:BE request model I have in the proxy, and do multiple BE requests, like one for each seek, but I think this would lead to balooning ops cost and possibly egress fees from overread/terminated reads. It'd also probably be slow.

For what it's worth, I gave this an evening's effort, seen in [this branch](https://github.com/domZippilli/gcs-proxy-cloud-run/tree/feature/httpservecontent). Unfortunately it doesn't work (error is "seeker can't seek"), and I'm fairly sure it's precisely because `ServeContent` wants to rewind the seeker. Beyond that, I also noted some undefined behaviors if one uses Ranges with filter pipelines that change body contents.

I think instead of getting all the goodies of `http.ServeContent` (which are unfortunately not worth the store-and-forward cost), we could implement support for the Range header directly, which should make Safari happier. I know it likes to send Range headers even for full-size requests sometimes.

**Comment by ToMGitHubN** [comment]
Thank you for working in your busy schedule.

It's a pity that we can't include the seek feature.
I understand that the seek function is not suitable for gcs-proxy-cloud-run. 

I close this issue.
Thank you.
